Added grades publishing feature.
ExtensionEngine/edx-sga pull request #10
Opened 2017-12-15 09:24 UTC by iivic

NDPD-832

2018-01-18 09:34 UTC, marjev requested changes
Also fix the conflicts and bump the version of the package.

2018-01-18 09:34 UTC, marjev commented on edx_sga/sga.py
> +from distutils.util import strtobool
nitpick: order of imports

2018-01-18 09:34 UTC, marjev commented on edx_sga/sga.py
> +        self.grades_published = bool(strtobool(request.params.get('grades_published')))
`json.loads(request.params.get('grades_published'))`

2018-01-18 09:34 UTC, marjev commented on edx_sga/static/js/src/edx_sga.js
> +function StaffGradedAssignmentXBlock(runtime, element, backendData) {
Call this `options` or something more generic, other than backendData. You named it to describe where it comes from, but not what it's expected to have or do. `runtime` and `element` are generic, but descriptive enough if you're familiar with the concept of an XBlock.

2018-01-18 09:34 UTC, marjev commented on edx_sga/static/js/src/edx_sga.js
> +        var updateGradesPublishedUrl = runtime.handlerUrl(element, 'update_grades_published')
nitpick: alphabetize

2018-01-18 09:34 UTC, marjev commented on edx_sga/templates/staff_graded_assignment/show.html
> +      </div>
https://www.google.hr/search?client=firefox-b-ab&dcr=0&biw=1280&bih=615&tbm=isch&sa=1&ei=V2RgWoeVOMmlsgHFiYa4Ag&q=checkbox+labels&oq=checkbox+labels&gs_l=psy-ab.3..0i24k1.12613.14293.0.14956.9.6.1.2.2.0.175.783.1j5.6.0....0...1c.1.64.psy-ab..0.9.803...0j0i5i30k1j0i8i30k1j0i13k1.0.zqqrH_G6A_c#imgrc=tTFAUIslSjY1cM:


Notice the difference.

2018-01-19 08:40 UTC, iivic commented
@marjev Please take another look.

2018-01-22 08:03 UTC, marjev approved these changes

2018-01-22 08:04 UTC, merged