NDPD-1254: Check for score before creating empty submission.
ExtensionEngine/edx-sga pull request #34
Opened 2018-05-18 13:56 UTC by vkaracic

2018-05-18 14:33 UTC, marjev requested changes

2018-05-18 14:33 UTC, marjev commented on edx_sga/sga.py
> +                    module.student.username
I think module is not yet defined in this context. I think line 575 introduces it.

2018-05-18 14:33 UTC, marjev commented
Also, version bump

2018-05-18 14:48 UTC, vkaracic commented
@marjev comments addressed!

2018-05-18 14:49 UTC, marjev approved these changes

2018-05-19 06:36 UTC, marjev commented
Also, should we add the check on the front end side as well?

2018-05-21 07:06 UTC, vkaracic commented
There were checks on the frontend but they didn't work because it turns out, and you'll love this, `Number('')` returns a `0` value. #programminglanguagegoals

2018-05-21 07:54 UTC, marjev commented
![image](https://user-images.githubusercontent.com/6833568/40296414-cb22c448-5cdc-11e8-960c-833f6bc747ca.png)

![image](https://user-images.githubusercontent.com/6833568/40296454-ecc91002-5cdc-11e8-9f8f-be09399ff6db.png)

2018-05-21 08:11 UTC, merged